### ISSUE TITLE
Create CommandHandlers related to Portfolio

### ISSUE THREAD

**Issue by venusvavadiya** [venusvavadiya/ticksbook-main#10]
- [x] `CreatePortfolioCommandHandler`
- [x] `RenamePortfolioCommandHandler`
- [x] `ArchivePortfolioCommandHandler`
- [x] `UnarchivePortfolioCommandHandler`
- [x] Inherit current domain exceptions from `AggregateExceptions`

**Comment by shailscript** [comment]
@ronakmistry36 Can you please take the `UnarchivePortfolioCommandHandler`?

**Comment by ronakmistry36** [comment]
> @ronakmistry36 Can you please take the `UnarchivePortfolioCommandHandler`?

sure !

**Comment by ronakmistry36** [comment]
@shailscript please give me a heads up once you are done with https://github.com/venusvavadiya/ticksbook-main/pull/18, there are some blocking changes requested by Venus.  
Thanks 😸

**Comment by shailscript** [comment]
@ronakmistry36 I am done with the `ArchivePortfolioCommandHandler` so you can pick it up from there in that PR if you like. I have added you to the PR too just in case.

Since it's async we would have to find ways to unblock people. The other way is to branch-off from #18 and add your code. I prefer this one.
